
---
name: "Simple Github Action"

on:
  push:
    branches:
      - master
      - testing

jobs:

  build:
    runs-on: ubuntu-latest


    steps:


      - name: "Install Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      - name: "Check terraform version"
        run: terraform --version
        shell: bash


      - name: "RUN script"
        run: |
             chmod +x script.sh
             ./script.sh
        shell: bash
