
---
name: "Simple Github Action"

on:
  push:
    branches:
      - master
      - testing

jobs:

  build:
    runs-on: ubuntu-latest


    steps:


      - name: "Run the date"
        run: date
        shell: bash

      - name: "OS list"
        run: cat /etc/os-release
        shell: bash

      - name: "who am i"
        run: whoami
        shell: bash

      - name: "List Directory"
        run: |
             pwd
             ls -la
             date
        shell: bash

      - name: "Checkout"
        uses: actions/checkout@v3
      

      - name: "clone"
        run: |
             sudo apt install git
             git clone https://github.com/Fujikomalan/aws-elb-site.git

      - name: "List Directory"
        run: |
             pwd
             ls -la
        shell: bash


      - name: "RUN script"
        run: |
             chmod +x script.sh
             ./script.sh
        shell: bash
